[
DEFAULT
]
subsuite
=
"
screenshots
"
support
-
files
=
[
"
.
.
/
head
.
js
"
]
[
"
browser_controlCenter
.
js
"
]
https_first_disabled
=
true
skip
-
if
=
[
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
10
.
15
'
&
&
arch
=
=
'
x86_64
'
"
#
macosx1014
times
out
see
bug
1554821
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
14
.
70
'
&
&
arch
=
=
'
x86_64
'
"
#
macosx1014
times
out
see
bug
1554821
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
15
.
30
'
&
&
arch
=
=
'
aarch64
'
"
#
macosx1014
times
out
see
bug
1554821
]
