[
DEFAULT
]
[
"
ShowSSEConfig
"
]
[
"
TestAlgorithm
"
]
[
"
TestArm64Disassembler
"
]
run
-
if
=
[
"
os
=
=
'
win
'
&
&
arch
=
=
'
aarch64
'
"
]
[
"
TestArray
"
]
[
"
TestArrayUtils
"
]
[
"
TestAtomicBitfields
"
]
[
"
TestAtomics
"
]
[
"
TestBaseProfiler
"
]
skip
-
if
=
[
"
tsan
"
#
Bug
1804081
]
[
"
TestBinarySearch
"
]
[
"
TestBitSet
"
]
[
"
TestBloomFilter
"
]
[
"
TestBufferList
"
]
[
"
TestCasting
"
]
[
"
TestCeilingFloor
"
]
[
"
TestCheckedInt
"
]
[
"
TestCompactPair
"
]
[
"
TestCountPopulation
"
]
[
"
TestCountZeroes
"
]
[
"
TestCrossProcessWin
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestDefineEnum
"
]
[
"
TestDllBlocklistAssumptions
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestDllInterceptor
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestDllInterceptorCrossProcess
"
]
run
-
if
=
[
"
os
=
=
'
win
'
&
&
arch
!
=
'
aarch64
'
"
]
[
"
TestDoublyLinkedList
"
]
[
"
TestEndian
"
]
[
"
TestEnumSet
"
]
[
"
TestEnumTypeTraits
"
]
[
"
TestEnumeratedArray
"
]
[
"
TestFastBernoulliTrial
"
]
[
"
TestFloatingPoint
"
]
[
"
TestFunctionRef
"
]
[
"
TestFunctionTypeTraits
"
]
[
"
TestHashTable
"
]
[
"
TestIATPatcher
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
skip
-
if
=
[
"
os
=
=
'
android
'
&
&
os_version
=
=
'
14
'
&
&
arch
=
=
'
aarch64
'
"
#
requires
administrator
permission
on
aarch64
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
15
.
30
'
&
&
arch
=
=
'
aarch64
'
"
#
requires
administrator
permission
on
aarch64
"
os
=
=
'
win
'
&
&
os_version
=
=
'
11
.
26100
'
&
&
arch
=
=
'
aarch64
'
"
"
os
=
=
'
win
'
&
&
os_version
=
=
'
11
.
26100
'
&
&
arch
=
=
'
x86
'
"
#
fails
on
win
/
x86
]
[
"
TestIntegerPrintfMacros
"
]
[
"
TestIntegerRange
"
]
[
"
TestJSONWriter
"
]
[
"
TestLauncherRegistryInfo
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestLinkedList
"
]
[
"
TestMMPolicy
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestMacroArgs
"
]
[
"
TestMacroForEach
"
]
[
"
TestMathAlgorithms
"
]
[
"
TestMaybe
"
]
[
"
TestMemoryPressureWatcherLinux
"
]
run
-
if
=
[
"
os
=
=
'
linux
'
"
]
[
"
TestMozCrash
"
]
skip
-
if
=
[
"
asan
"
"
os
=
=
'
android
'
&
&
os_version
=
=
'
14
'
&
&
arch
=
=
'
aarch64
'
"
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
10
.
15
'
&
&
arch
=
=
'
x86_64
'
"
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
14
.
70
'
&
&
arch
=
=
'
x86_64
'
"
"
os
=
=
'
mac
'
&
&
os_version
=
=
'
15
.
30
'
&
&
arch
=
=
'
aarch64
'
"
"
os
=
=
'
win
'
&
&
os_version
=
=
'
10
.
2009
'
&
&
arch
=
=
'
x86_64
'
"
"
os
=
=
'
win
'
&
&
os_version
=
=
'
11
.
26100
'
&
&
arch
=
=
'
x86
'
"
"
os
=
=
'
win
'
&
&
os_version
=
=
'
11
.
26100
'
&
&
arch
=
=
'
x86_64
'
"
"
os
=
=
'
win
'
&
&
os_version
=
=
'
11
.
26100
'
&
&
arch
=
=
'
aarch64
'
"
]
[
"
TestMozJemallocUtils
"
]
[
"
TestNativeNt
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestNonDereferenceable
"
]
[
"
TestNotNull
"
]
[
"
TestOleAut32Initialization
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestPEExportSection
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestPoisonArea
"
]
skip
-
if
=
[
"
asan
"
#
Not
built
on
sanitizer
builds
"
tsan
"
]
[
"
TestPrintf
"
]
[
"
TestRandomNum
"
]
[
"
TestRange
"
]
[
"
TestRefPtr
"
]
[
"
TestResult
"
]
[
"
TestRollingMean
"
]
[
"
TestSHA1
"
]
[
"
TestSIMD
"
]
[
"
TestSPSCQueue
"
]
[
"
TestSafeThreadLocal
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestSameBinary
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestSaturate
"
]
[
"
TestScopeExit
"
]
[
"
TestSegmentedVector
"
]
[
"
TestSharedMappingCommit
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestSmallPointerArray
"
]
[
"
TestSplayTree
"
]
[
"
TestStackCookie
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestStackWalkInitialization
"
]
run
-
if
=
[
"
os
=
=
'
win
'
&
&
arch
=
=
'
x86_64
'
"
]
[
"
TestTextUtils
"
]
[
"
TestThreadSafeWeakPtr
"
]
[
"
TestTimeStampWin
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestTypedEnum
"
]
[
"
TestUniquePtr
"
]
[
"
TestUriValidation
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestUtf8
"
]
[
"
TestVariant
"
]
[
"
TestVector
"
]
[
"
TestWeakPtr
"
]
[
"
TestWinArchDefs
"
]
run
-
if
=
[
"
os
=
=
'
win
'
"
]
[
"
TestWrappingOperations
"
]
[
"
TestXorShift128PlusRNG
"
]
