[
DEFAULT
]
tags
=
"
devtools
"
subsuite
=
"
devtools
"
support
-
files
=
[
"
allocation
-
tracker
.
js
"
"
cc
-
analyzer
.
sys
.
mjs
"
"
trace
-
objects
.
sys
.
mjs
"
]
[
"
browser_allocation_tracker
.
js
"
]
run
-
if
=
[
"
os
=
=
'
linux
'
&
&
os_version
=
=
'
22
.
04
'
&
&
arch
=
=
'
x86_64
'
&
&
display
=
=
'
wayland
'
&
&
opt
"
#
Results
should
be
platform
agnostic
-
only
run
on
linux64
-
opt
"
os
=
=
'
linux
'
&
&
os_version
=
=
'
24
.
04
'
&
&
arch
=
=
'
x86_64
'
&
&
display
=
=
'
x11
'
&
&
opt
"
#
Results
should
be
platform
agnostic
-
only
run
on
linux64
-
opt
]
skip
-
if
=
[
"
verify
"
#
Bug
1730507
-
objects
without
stacks
get
allocated
during
the
GC
of
the
first
test
when
running
multiple
times
.
]
[
"
browser_dump_scope
.
js
"
]
