[
package
]
name
=
"
widget_windows
"
version
=
"
0
.
1
.
0
"
edition
=
"
2021
"
#
See
more
keys
and
their
definitions
at
https
:
/
/
doc
.
rust
-
lang
.
org
/
cargo
/
reference
/
manifest
.
html
[
dependencies
]
libc
=
"
0
.
2
"
nserror
=
{
path
=
"
.
.
/
.
.
/
.
.
/
xpcom
/
rust
/
nserror
"
}
nsstring
=
{
path
=
"
.
.
/
.
.
/
.
.
/
xpcom
/
rust
/
nsstring
"
}
thin
-
vec
=
{
version
=
"
0
.
2
.
1
"
features
=
[
"
gecko
-
ffi
"
]
}
xpcom
=
{
path
=
"
.
.
/
.
.
/
.
.
/
xpcom
/
rust
/
xpcom
"
}
[
dependencies
.
windows
]
version
=
"
0
.
62
.
0
"
features
=
[
"
UI_Notifications
"
]
[
dependencies
.
windows
-
collections
]
version
=
"
0
.
3
.
0
"
